version: "3"

services:
  boardgames:
    build: ..
    environment:
      - DB_HOST=postgres
      - POSTGRES_PASSWORD=boardgames
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=boardgames
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
